baseurl: "/ena-website" # for deployment to gh-pages
# baseurl: "" # for testing locally

# Site settings
title: Emergency Needs Assessment

# locale settings
default_locale:     "en"
authorized_locales: ["en","es"]